name: Hellbomb Script Cross-platform PowerShell Test Suite

on:
  push:
    branches: [ main ]
    paths:
      - "Hellbomb Script.ps1"
  pull_request:
    branches: [ main ]
    paths:
      - "Hellbomb Script.ps1"
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: windows-latest
            shell: powershell  # This triggers Windows PowerShell 5.1
            title: "Native Windows PS"
          - os: ubuntu-latest
            shell: pwsh        # This triggers PowerShell Core
            title: "Ubuntu PowerShell Core"
      fail-fast: false

    name: ${{ matrix.title }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Pester
        shell: ${{ matrix.shell }}
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Run Pester Tests
        shell: ${{ matrix.shell }}
        run: |
          # The $PSVersionTable variable will show the differences in logs
          Write-Host "Running on: $($PSVersionTable.PSVersion)"
          Invoke-Pester -Path "./HellbombScript.Tests.ps1" -Output Detailed
